spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-api-demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 111111
  lifecycle:
    timeout-per-shutdown-phase: 60s # 设置缓冲期，最大等待时间