server:
  port: 80
  servlet:
    context-path: /zt
  shutdown: graceful # 开启优雅停机，默认immediate是立即关机
  undertow:
    accesslog:
      enabled: false # 是否打开 undertow 日志，默认为 false
      dir: logs # 设置访问日志所在目录
    io: 2 # 指定工作者线程的 I/0 线程数，默认为 2 或者 CPU 的个数
    worker: 16 # 指定工作者线程个数，默认为 I/O 线程个数的 8 倍
    max-http-post-size: 0 # 设置 HTTP POST 内容的最大长度，默认不做限制



spring:
  datasource:
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-api-demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&failOverReadOnly=false
  lifecycle:
    timeout-per-shutdown-phase: 60s # 设置缓冲期，最大等待时间
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器连接端口
    port: 6379
    password: # Redis服务器连接密码（默认为空）
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
      timeout: 30000 # 连接超时时间（毫秒）
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/static/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
  main:
    allow-bean-definition-overriding: true
  elasticjob:
    #注册中心配置
    zookeeper:
      server-lists: 192.168.115.205:2181
      namespace: dd-job01
    #简单作业配置
    simples:
      #spring简单作业示例配置
      spring-simple-job:
        #配置简单作业，必须实现com.dangdang.ddframe.job.api.simple.SimpleJob
        job-class: com.demo.modules.bussiness.job.MyJob
        cron: 0/2 * * * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=Beijing,1=Shanghai,2=Guangzhou
        #配置监听器
        listener:
          #配置每台作业节点均执行的监听，必须实现com.dangdang.ddframe.job.lite.api.listener.ElasticJobListener
          listener-class: com.demo.modules.bussiness.job.JobListener

management:
  health:
    redis:
      enabled: false # 关闭redis连接健康检查



mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
  type-handlers-package: com.tenmao.handler


# zookeeper集群
elaticjob:
  zookeeper:
    server-lists: 192.168.0.205:2181
    namespace: dd-job

test:
  name: 张三